title: Still Entropy by Hafizul
theme: minima

show_excerpts: true
markdown: kramdown
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.mdheader_pages:
  - about.md

author: Hafizul Abdullah
social_links:
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/mohafizul/" }