# Dependencies
markdown:         kramdown
remote_theme: mdo/hyde
plugins:
  - jekyll-feed
  # - jekyll-paginate

# Setup
title: Process Eng.
tagline:          'A Jekyll theme'
description:      'Technical Lesson Learnt & Random Observations'
email: your-email@example.com
baseurl: / # the subpath of your site, e.g. /blog
paginate:            5
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


