title: Still Entropy by Hafizul
author:
  name: Hafizul Abdullah
theme: minima

show_excerpts: true
markdown: kramdown
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.mdheader_pages:
  - about.md

social_links:
  - icon: linkedin
  - url: "https://www.linkedin.com/in/mohafizul/"