title: Still Entropy by Hafizul
author:
  name: 2025 Hafizul Abdullah
theme: minima

show_excerpts: true
markdown: kramdown
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages: about.md

social_links:
  - title: linkedin Hafizul Abdullah
    icon: linkedin
    url: "https://www.linkedin.com/in/mohafizul/"

hide_site_feed_link: true